# Generated by Django 5.2.8 on 2025-11-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor'),
        ('appointments', '0004_alter_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
