# Generated by Django 5.2.8 on 2025-12-02 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('therapy_updates', models.BooleanField(default=True)),
                ('doctor_messages', models.BooleanField(default=True)),
                ('default_reminder_time', models.IntegerField(default=24)),
                ('preferred_center_id', models.IntegerField(blank=True, null=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('ayurvedic_body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('time_format', models.CharField(choices=[('12', '12-hour'), ('24', '24-hour')], default='12', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
