# Generated by Django 5.2.8 on 2025-12-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_email_6f6f26_idx',
            old_name='accounts_pas_email_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_affdf2_idx',
            old_name='accounts_pas_token_idx',
        ),
    ]
