# Generated by Django 5.2.8 on 2025-12-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_accounts_pas_email_idx_accounts_pa_email_6f6f26_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
