# Generated by Django 5.2.8 on 2025-11-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_token',
            field=models.TextField(),
        ),
    ]
