# Generated by Django 5.2.8 on 2025-11-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_doctor'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Center',
        ),
    ]
