# Generated by Django 5.2.8 on 2025-11-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='centers.center'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='timing',
            field=models.CharField(blank=True, choices=[('10am-2pm', '10:00 AM - 2:00 PM'), ('2pm-6pm', '02:00 PM - 06:00 PM'), ('6pm-10pm', '06:00 PM - 10:00 PM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked-in'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
    ]
