# Generated by Django 5.2.8 on 2025-11-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_panchakarmaprocedure_treatmentplan_invoice_and_more'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
