# Generated by Django 5.2.8 on 2025-12-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_checked_in_at_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='therapist',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked-in'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
    ]
