# Generated by Django 5.2.8 on 2025-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='current_health_condition',
            new_name='menstrual_history',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addictions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='body_type_tendency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='contraindications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_symptoms',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Moderate', 'Moderate'), ('Active', 'Active')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_medical_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='prakriti',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_communication',
            field=models.CharField(blank=True, choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], default='WhatsApp', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pulse_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='seasonal_allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='treatment_goals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='vikriti',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='current_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
