# Generated by Django 5.2.8 on 2025-11-27 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_current_health_condition_patientprofile_menstrual_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='weight',
            new_name='weight_kg',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='addictions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='contraindications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='current_symptoms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='past_medical_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='treatment_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
