# Generated by Django 5.2.8 on 2025-11-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_height_patientprofile_height_cm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='height_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
