# Generated by Django 5.2.8 on 2025-11-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_height_cm_patientprofile_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='weight',
            new_name='weight_kg',
        ),
    ]
