# Generated by Django 5.2.8 on 2025-12-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_height_patientprofile_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='first_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
