# Generated by Django 5.2.8 on 2025-12-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprofile_first_visit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='first_visit_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_visit_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='total_visits',
        ),
    ]
