# Generated by Django 5.2.8 on 2025-12-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='center',
            name='available_services',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='center',
            name='doctors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='center',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='center',
            name='specialties',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='center',
            name='timing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='center',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_set', to='clinic.center'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='timing',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
