# Generated by Django 5.2.8 on 2025-12-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_center_specialties_inventoryitem_therapist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='specialties',
            field=models.JSONField(default=list),
        ),
    ]
